### ISSUE TITLE
Submit button shows disabled always

### ISSUE THREAD

**Issue by patriksharma** [IvanVorobei/RateApp#1]
I have implemented it perfectly. Submit button always shows disabled. 

![screen shot 2017-08-27 at 1 49 24 pm](https://user-images.githubusercontent.com/383524/29748168-abb10532-8b2e-11e7-8c4e-534f1826d484.png)

**Comment by IvanVorobei** [comment]
App in AppStore?

**Comment by patriksharma** [comment]
App is approved but i have not make it  "ready for sale".

Do I need to make it ready for sale first ?

**Comment by IvanVorobei** [comment]
Of course
How module can set stars to app, which not publish in app-store

**Comment by patriksharma** [comment]
@IvanVorobei  I have tried changing the ID with live app. but still it didn't showed up. Any idea ?

**Comment by IvanVorobei** [comment]
@patriksharma show me link app in App Store

**Comment by patriksharma** [comment]
https://itunes.apple.com/us/app/college-universe/id1166560823?mt=8

**Comment by patriksharma** [comment]
worked for you  @IvanVorobei 
?

**Comment by IvanVorobei** [comment]
@patriksharma I can not download, I have other store region
