### ISSUE TITLE
 If I use the method to set the time interval how would I actually present the banner itself?

### ISSUE THREAD

**Issue by msa789** [IvanVorobei/RateApp#2]
Hi.

Should I still present the banner if I am setting a time interval?

Is this correct code?

        SPRateApp.dialog.bannerWithIndicator.present(on: self, applicationID: "1241292508", dataSource: RateAppDataSource())
        SPRateApp.setTimeInterval(days: 3)

**Comment by IvanVorobei** [comment]
Correct way!
